GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-type: application/json

{
    "name": "Shreyas",
    "password": "784654" 
}

###

POST http://localhost:3000/users/login
Content-type: application/json

{
    "name": "Shreyas",
    "password": "784654" 
}